version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Check Prettier, ESLint, Flow
          command: yarn ci-check
